import {
  faWandMagicSparkles,
  faShieldHalved,
  faFilter,
  faGear,
  faBarcode,
  faFolder,
  faFolderOpen,
  faGears,
  faNetworkWired,
  faSitemap,
  faKeyboard,
  faCodeBranch,
  faWebAwesome,
  faTerminal,
  faRectangleXmark,
  faDiagramProject,
  faCubes,
  faCodeMerge,
  faCodeCommit,
  faBarsStaggered,
} from "@fortawesome/free-solid-svg-icons";

export const logos = [
  faWandMagicSparkles,
  faShieldHalved,
  faFilter,
  faGear,
  faBarcode,
  faFolder,
  faFolderOpen,
  faGears,
  faNetworkWired,
  faSitemap,
  faKeyboard,
  faCodeBranch,
  faWebAwesome,
  faTerminal,
  faRectangleXmark,
  faDiagramProject,
  faCubes,
  faCodeMerge,
  faCodeCommit,
  faBarsStaggered,
  faWandMagicSparkles,
  faShieldHalved,
  faFilter,
  faGear,
  faBarcode,
  faFolder,
  faFolderOpen,
  faGears,
  faNetworkWired,
] as const;
